version: '3.5'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - ${DB_PORT}:27017
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
